In [46]:
import numpy as np
import pandas as pd

# Importing The Data

In [47]:
df = pd.read_csv('Salary_Data.csv')

In [48]:
X = df.iloc[:, :-1].values
y = df.iloc[:, 1:].values

In [49]:
X, y

(array([[ 1.1],
        [ 1.3],
        [ 1.5],
        [ 2. ],
        [ 2.2],
        [ 2.9],
        [ 3. ],
        [ 3.2],
        [ 3.2],
        [ 3.7],
        [ 3.9],
        [ 4. ],
        [ 4. ],
        [ 4.1],
        [ 4.5],
        [ 4.9],
        [ 5.1],
        [ 5.3],
        [ 5.9],
        [ 6. ],
        [ 6.8],
        [ 7.1],
        [ 7.9],
        [ 8.2],
        [ 8.7],
        [ 9. ],
        [ 9.5],
        [ 9.6],
        [10.3],
        [10.5]]),
 array([[ 39343.],
        [ 46205.],
        [ 37731.],
        [ 43525.],
        [ 39891.],
        [ 56642.],
        [ 60150.],
        [ 54445.],
        [ 64445.],
        [ 57189.],
        [ 63218.],
        [ 55794.],
        [ 56957.],
        [ 57081.],
        [ 61111.],
        [ 67938.],
        [ 66029.],
        [ 83088.],
        [ 81363.],
        [ 93940.],
        [ 91738.],
        [ 98273.],
        [101302.],
        [113812.],
        [109431.],
        [105582.],
        [116969.],
     

# Data Preprocessing

## Splitting The Data

In [50]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [51]:
X_train, X_test

(array([[ 9.6],
        [ 4. ],
        [ 5.3],
        [ 7.9],
        [ 2.9],
        [ 5.1],
        [ 3.2],
        [ 4.5],
        [ 8.2],
        [ 6.8],
        [ 1.3],
        [10.5],
        [ 3. ],
        [ 2.2],
        [ 5.9],
        [ 6. ],
        [ 3.7],
        [ 3.2],
        [ 9. ],
        [ 2. ],
        [ 1.1],
        [ 7.1],
        [ 4.9],
        [ 4. ]]),
 array([[ 1.5],
        [10.3],
        [ 4.1],
        [ 3.9],
        [ 9.5],
        [ 8.7]]))

In [52]:
y_train, y_test

(array([[112635.],
        [ 55794.],
        [ 83088.],
        [101302.],
        [ 56642.],
        [ 66029.],
        [ 64445.],
        [ 61111.],
        [113812.],
        [ 91738.],
        [ 46205.],
        [121872.],
        [ 60150.],
        [ 39891.],
        [ 81363.],
        [ 93940.],
        [ 57189.],
        [ 54445.],
        [105582.],
        [ 43525.],
        [ 39343.],
        [ 98273.],
        [ 67938.],
        [ 56957.]]),
 array([[ 37731.],
        [122391.],
        [ 57081.],
        [ 63218.],
        [116969.],
        [109431.]]))

## Feature Scaling 

In [53]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [54]:
X_test, X_train

(array([[-1.37762723],
        [ 2.02933848],
        [-0.37102373],
        [-0.44845477],
        [ 1.71961432],
        [ 1.40989017]]),
 array([[ 1.75832984],
        [-0.40973925],
        [ 0.09356251],
        [ 1.10016601],
        [-0.83560996],
        [ 0.01613147],
        [-0.7194634 ],
        [-0.21616165],
        [ 1.21631257],
        [ 0.6742953 ],
        [-1.45505827],
        [ 2.10676952],
        [-0.79689444],
        [-1.1066186 ],
        [ 0.32585562],
        [ 0.36457114],
        [-0.52588581],
        [-0.7194634 ],
        [ 1.52603672],
        [-1.18404964],
        [-1.53248931],
        [ 0.79044186],
        [-0.06129957],
        [-0.40973925]]))

# Building And Training The Model

In [55]:
from sklearn.linear_model import LinearRegression

regression = LinearRegression()
regression.fit(X_train, y_train)

LinearRegression()

In [56]:
y_pred = regression.predict(X_test)

In [60]:
r2_score = regression.score(X_test, y_test)
print(r2_score*100)

98.8169515729126


## Creating Cross Validation

In [65]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(LinearRegression(), X, y, cv=10, scoring='neg_mean_squared_error')

In [66]:
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

-38326951.10 accuracy with a standard deviation of 17112217.48
